spring:
  application:
    name: "DevOpsAutomation"
  task:
    scheduling:
      pool:
        size: 10
  datasource:
    username: root
    password: rootroot
    url: "jdbc:mysql://localhost:3306/dev2"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 465
    username: devwhenry@gmail.com
    password: dmkj mopg cmgs rjoj
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

logging:
  file:
    name: "log/service2.log"

server:
  port: 9100

